# Generated by Django 5.2.4 on 2025-07-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("choice_a", models.CharField(max_length=100)),
                ("choice_b", models.CharField(max_length=100)),
                ("choice_c", models.CharField(max_length=100)),
                (
                    "correct_choice",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C")], max_length=1
                    ),
                ),
            ],
        ),
    ]
