# Generated by Django 5.2.4 on 2025-08-02 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_testresult"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game_type",
                    models.CharField(
                        choices=[
                            ("vocabblitz", "VocabBlitz"),
                            ("grammar_typer", "Grammar Typer"),
                            ("sentence_master", "Cümle Ustası"),
                            ("pronunciation", "Telaffuz"),
                            ("ai_roleplay", "AI Roleplay"),
                            ("placement_test", "Seviye Testi"),
                            ("ai_questions", "AI Sorular"),
                        ],
                        max_length=20,
                    ),
                ),
                ("score", models.IntegerField()),
                ("xp_gained", models.IntegerField()),
                ("played_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("başlangıç", "Başlangıç"),
                            ("orta", "Orta"),
                            ("ileri", "İleri"),
                            ("uzman", "Uzman"),
                        ],
                        default="başlangıç",
                        max_length=20,
                    ),
                ),
                ("level_number", models.IntegerField(default=1)),
                ("total_xp", models.IntegerField(default=0)),
                ("current_xp", models.IntegerField(default=0)),
                ("xp_to_next_level", models.IntegerField(default=1000)),
                ("daily_streak", models.IntegerField(default=0)),
                ("last_activity_date", models.DateField(auto_now=True)),
                ("games_played", models.IntegerField(default=0)),
                ("total_score", models.IntegerField(default=0)),
                ("average_score", models.IntegerField(default=0)),
                ("vocabulary_progress", models.IntegerField(default=0)),
                ("grammar_progress", models.IntegerField(default=0)),
                ("pronunciation_progress", models.IntegerField(default=0)),
                ("translation_progress", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
